# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GermesWind.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Germes(object):
    def setupUi(self, Germes):
        Germes.setObjectName("Germes")
        Germes.resize(729, 413)
        self.centralwidget = QtWidgets.QWidget(Germes)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.video = QtWidgets.QLabel(self.centralwidget)
        self.video.setGeometry(QtCore.QRect(-4, -8, 741, 421))
        self.video.setAutoFillBackground(False)
        self.video.setText("")
        self.video.setObjectName("video")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 170, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 731, 421))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0454545 rgba(52, 70, 102, 255), stop:1 rgba(79, 68, 127, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Name = QtWidgets.QLabel(self.frame)
        self.Name.setGeometry(QtCore.QRect(130, 40, 481, 191))
        self.Name.setAutoFillBackground(False)
        self.Name.setStyleSheet("font: 73pt \"Orbitron\";\n"
"text-shadow: 2px 3px 7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.Name.setTextFormat(QtCore.Qt.PlainText)
        self.Name.setScaledContents(False)
        self.Name.setAlignment(QtCore.Qt.AlignCenter)
        self.Name.setObjectName("Name")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(170, 270, 411, 31))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border-style:none;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"border-radius:10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 63, 255, 255), stop:1 rgba(14, 123, 255, 255));\n"
"}")
        self.progressBar.setProperty("value", 100)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.Graph = PlotWidget(self.centralwidget)
        self.Graph.setGeometry(QtCore.QRect(230, 140, 271, 121))
        self.Graph.setObjectName("Graph")
        self.video.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.frame.raise_()
        self.Graph.raise_()
        Germes.setCentralWidget(self.centralwidget)

        self.retranslateUi(Germes)
        QtCore.QMetaObject.connectSlotsByName(Germes)

    def retranslateUi(self, Germes):
        _translate = QtCore.QCoreApplication.translate
        Germes.setWindowTitle(_translate("Germes", "Project \"Germes\""))
        self.label_2.setText(_translate("Germes", "TextLabel"))
        self.label_3.setText(_translate("Germes", "TextLabel"))
        self.Name.setText(_translate("Germes", "Germes"))
from pyqtgraph import PlotWidget
